![Parked motorcycle](motorcycle.jpg)

You're working for a company that sells motorcycle parts, and they've asked for some help in analyzing their sales data!

They operate three warehouses in the area, selling both retail and wholesale. They offer a variety of parts and accept credit cards, cash, and bank transfer as payment methods. However, each payment type incurs a different fee.

The board of directors wants to gain a better understanding of wholesale revenue by product line, and how this varies month-to-month and across warehouses. You have been tasked with calculating net revenue for each product line and grouping results by month and warehouse. The results should be filtered so that only `"Wholesale"` orders are included.

They have provided you with access to their database, which contains the following table called `sales`:

## Sales
| Column | Data type | Description |
|--------|-----------|-------------|
| `order_number` | `VARCHAR` | Unique order number. |
| `date` | `DATE` | Date of the order, from June to August 2021. |
| `warehouse` | `VARCHAR` | The warehouse that the order was made from&mdash; `North`, `Central`, or `West`. |
| `client_type` | `VARCHAR` | Whether the order was `Retail` or `Wholesale`. |
| `product_line` | `VARCHAR` | Type of product ordered. |
| `quantity` | `INT` | Number of products ordered. | 
| `unit_price` | `FLOAT` | Price per product (dollars). |
| `total` | `FLOAT` | Total price of the order (dollars). |
| `payment` | `VARCHAR` | Payment method&mdash;`Credit card`, `Transfer`, or `Cash`. |
| `payment_fee` | `FLOAT` | Percentage of `total` charged as a result of the `payment` method. |


Your query output should be presented in the following format:

| `product_line` | `month` | `warehouse` |	`net_revenue` |
|----------------|-----------|----------------------------|--------------|
| product_one | --- | --- | --- |
| product_one | --- | --- | --- |
| product_one | --- | --- | --- |
| product_one | --- | --- | --- |
| product_one | --- | --- | --- |
| product_one | --- | --- | --- |
| product_two | --- | --- | --- |
| ... | ... | ... | ... |

In [3]:
SELECT 
  product_line,
  EXTRACT(MONTH FROM date) AS month,
  warehouse,
  SUM(total * (1 - payment_fee)) AS net_revenue
FROM 
  sales
WHERE 
  client_type = 'Wholesale'
GROUP BY 
  product_line, month, warehouse
ORDER BY 
  product_line, month, warehouse;

             product_line  month warehouse  net_revenue
0         Breaking system      6   Central    3648.1401
1         Breaking system      6     North    1472.9319
2         Breaking system      6      West    1200.6423
3         Breaking system      7   Central    3740.9427
4         Breaking system      7     North    2568.5451
5         Breaking system      7      West    3030.3900
6         Breaking system      8   Central    3009.0951
7         Breaking system      8     North    1753.1910
8         Breaking system      8      West    2475.7128
9       Electrical system      6   Central    2875.9302
10      Electrical system      6     North    2002.3047
11      Electrical system      7   Central    5521.9428
12      Electrical system      7     North    1693.0584
13      Electrical system      7      West     444.9753
14      Electrical system      8   Central    3095.2152
15      Electrical system      8     North    4673.9880
16      Electrical system      8      West    1229.4513
17                 Engine      6   Central    6483.4011
18                 Engine      7   Central    1808.7696
19                 Engine      7     North     997.0785
20                 Engine      8   Central    9433.4823
21                 Engine      8     North    2300.9580
22           Frame & body      6   Central    5060.2860
23           Frame & body      6     North    4861.0782
24           Frame & body      6      West    2751.9624
25           Frame & body      7   Central    3103.8183
26           Frame & body      7     North    6093.1134
27           Frame & body      8   Central    8571.4992
28           Frame & body      8     North    7819.9506
29           Frame & body      8      West     821.4030
30          Miscellaneous      6   Central    1859.3388
31          Miscellaneous      6     North     508.8600
32          Miscellaneous      6      West    2258.1999
33          Miscellaneous      7   Central    3087.3051
34          Miscellaneous      7     North    2380.6332
35          Miscellaneous      7      West    1145.2617
36          Miscellaneous      8   Central    1722.4020
37          Miscellaneous      8     North    1823.0256
38          Miscellaneous      8      West     805.3056
39  Suspension & traction      6   Central    3291.7995
40  Suspension & traction      6     North    7985.1717
41  Suspension & traction      6      West    2348.8344
42  Suspension & traction      7   Central    6392.2320
43  Suspension & traction      7     North    3677.2065
44  Suspension & traction      7      West    2909.9763
45  Suspension & traction      8   Central    5362.5924
46  Suspension & traction      8     North    4874.5125
47  Suspension & traction      8      West    1069.9920

In [2]:
SELECT
  product_line,
  EXTRACT(MONTH FROM date) AS month,
  warehouse,
  SUM(total - total * payment_fee / 100) AS net_revenue
FROM sales
WHERE client_type = 'Wholesale'
GROUP BY product_line, EXTRACT(MONTH FROM date), warehouse
ORDER BY product_line, month, warehouse;

             product_line  month warehouse  net_revenue
0         Breaking system      6   Central  3684.621501
1         Breaking system      6     North  1487.661219
2         Breaking system      6      West  1212.648723
3         Breaking system      7   Central  3778.352127
4         Breaking system      7     North  2594.230551
5         Breaking system      7      West  3060.693900
6         Breaking system      8   Central  3039.186051
7         Breaking system      8     North  1770.722910
8         Breaking system      8      West  2500.469928
9       Electrical system      6   Central  2904.689502
10      Electrical system      6     North  2022.327747
11      Electrical system      7   Central  5577.162228
12      Electrical system      7     North  1709.988984
13      Electrical system      7      West   449.425053
14      Electrical system      8   Central  3126.167352
15      Electrical system      8     North  4720.727880
16      Electrical system      8      West  1241.745813
17                 Engine      6   Central  6548.235111
18                 Engine      7   Central  1826.857296
19                 Engine      7     North  1007.049285
20                 Engine      8   Central  9527.817123
21                 Engine      8     North  2323.967580
22           Frame & body      6   Central  5110.888860
23           Frame & body      6     North  4909.688982
24           Frame & body      6      West  2779.482024
25           Frame & body      7   Central  3134.856483
26           Frame & body      7     North  6154.044534
27           Frame & body      8   Central  8657.214192
28           Frame & body      8     North  7898.150106
29           Frame & body      8      West   829.617030
30          Miscellaneous      6   Central  1877.932188
31          Miscellaneous      6     North   513.948600
32          Miscellaneous      6      West  2280.781899
33          Miscellaneous      7   Central  3118.178151
34          Miscellaneous      7     North  2404.439532
35          Miscellaneous      7      West  1156.714317
36          Miscellaneous      8   Central  1739.626020
37          Miscellaneous      8     North  1841.255856
38          Miscellaneous      8      West   813.358656
39  Suspension & traction      6   Central  3324.717495
40  Suspension & traction      6     North  8065.023417
41  Suspension & traction      6      West  2372.322744
42  Suspension & traction      7   Central  6456.154320
43  Suspension & traction      7     North  3713.978565
44  Suspension & traction      7      West  2939.076063
45  Suspension & traction      8   Central  5416.218324
46  Suspension & traction      8     North  4923.257625
47  Suspension & traction      8      West  1080.691920